# https://taskfile.dev

version: "3"

tasks:
  default:
    - go build . && OPENAI_API_KEY=$(pass show i/openai.com-api-key| head -n 1) ./aicode

  t:
    - go build . && OPENAI_API_KEY=$(pass show i/openai.com-api-key| head -n 1) ./aicode -q "grep claude"

  build:
    - go build .
